### ISSUE TITLE
Can't run docker for generating maps

### ISSUE THREAD

**Issue by Vascom** [mapsme/dockerfiles#2]
I am try follow instructions in dockerfiles/maps_generator/README.md
But on stage
`$ docker run -v ~/Projects/generation:/mapsme/generation: --rm -t maps_generator --config=/mapsme/generation/config.ini --countries="Russia_Samara Oblast" --skip="coastline"`
I have errors:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/logging/handlers.py", line 437, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/mapsme/generation/generation.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 243, in <module>
    main()
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 233, in main
    env = Env(options)
  File "/mapsme/omim/tools/python/maps_generator/generator/env.py", line 69, in __init__
    Env._logging_setup()
  File "/mapsme/omim/tools/python/maps_generator/generator/env.py", line 277, in _logging_setup
    logging.config.dictConfig(settings.LOGGING)
  File "/usr/lib/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/mapsme/generation/generation.log'
```
Please help solve this problem.

**Comment by rnkyr** [comment]
I'm currently facing a similar issue. Any update here?

**Comment by Vascom** [comment]
I just switched to not use docker.
@rnkyr My instruction https://hide.webhop.me/mapsme/0_readme.txt

**Comment by rnkyr** [comment]
@Vascom, thanks a lot! will check
