### ISSUE TITLE
FileNotFoundError near to end of process.

### ISSUE THREAD

**Issue by alexx7676** [mapsme/dockerfiles#3]
1. Docker image was created by command: 
```$ docker build --build-arg TAG=release-101 -t maps_generator .```
2. Contents of .ini file:
```
[Main]
DEBUG: 0

[External]
PLANET_URL: http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf
PLANET_MD5_URL: http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
```
3. Command to run generator tool:
```$ docker run -v ~/projects/osm/generation:/mapsme/generation --rm -t maps_generator --config=/mapsme/generation/config.ini --countries="Uzbekistan" --skip="Coastline"```
4. After downloading subway data there is error:
```FileNotFoundError: [Errno 2] No such file or directory: ''```

**Comment by alexx7676** [comment]
generation.log:
```
[2020-07-31 10:53:00,321] INFO env Start setup ...
[2020-07-31 10:53:00,321] INFO env Create /mapsme/tmp ...
[2020-07-31 10:53:00,322] INFO env Check osm tools ...
[2020-07-31 10:53:00,322] INFO env Create /mapsme/osmctools ...
[2020-07-31 10:53:00,322] INFO env Build osm tools ...
[2020-07-31 10:53:04,416] INFO env Check generator tool ...
[2020-07-31 10:53:04,417] INFO env Find generator tool in /mapsme/omim-build-release ...
[2020-07-31 10:53:04,418] INFO env Generator found - /mapsme/omim-build-release/generator_tool
[2020-07-31 10:53:04,419] INFO env Build name is 2020_07_31__10_53_04.
[2020-07-31 10:53:04,419] INFO env Build path is /mapsme/generation/2020_07_31__10_53_04.
[2020-07-31 10:53:04,419] INFO env Create /mapsme/generation/2020_07_31__10_53_04 ...
[2020-07-31 10:53:04,420] INFO env Create /mapsme/generation/2020_07_31__10_53_04/intermediate_data ...
[2020-07-31 10:53:04,421] INFO env Create /mapsme/generation/2020_07_31__10_53_04/intermediate_data/borders ...
[2020-07-31 10:53:04,422] INFO env Create /mapsme/generation/2020_07_31__10_53_04/draft ...
[2020-07-31 10:53:04,422] INFO env Create /mapsme/generation/2020_07_31__10_53_04/osm2ft ...
[2020-07-31 10:53:04,423] INFO env The following 1 maps will build: Uzbekistan.
[2020-07-31 10:53:04,423] INFO env Finish setup
[2020-07-31 10:53:04,425] INFO env Create /mapsme/generation/2020_07_31__10_53_04/logs ...
[2020-07-31 10:53:04,426] INFO stages Stage DownloadAndConvertPlanet: start ...
[2020-07-31 10:53:04,427] INFO env Create /mapsme/generation/2020_07_31__10_53_04/status ...
[2020-07-31 10:53:04,434] INFO file Trying to download /mapsme/generation/2020_07_31__10_53_04/planet.osm.pbf from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.
[2020-07-31 10:53:04,434] INFO file Trying to download /mapsme/generation/2020_07_31__10_53_04/planet.osm.pbf.md5 from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5.
[2020-07-31 10:55:30,227] INFO file File /mapsme/generation/2020_07_31__10_53_04/planet.osm.pbf.md5 was downloaded from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5.
[2020-07-31 10:56:21,928] INFO file File /mapsme/generation/2020_07_31__10_53_04/planet.osm.pbf was downloaded from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.
[2020-07-31 10:56:24,185] INFO stages Stage DownloadAndConvertPlanet: finished in 0:03:19.758581
[2020-07-31 10:56:24,186] INFO stages Stage Preprocess: start ...
[2020-07-31 10:56:24,235] INFO gen_tool Run generator tool [generator_tool version 1596049554 c2d18fcf5f6962bbc232747afa940789355f5b64]: /mapsme/omim-build-release/generator_tool --threads_count=1 --intermediate_data_path=/mapsme/generation/2020_07_31__10_53_04/intermediate_data --osm_file_type=o5m --osm_file_name=/mapsme/generation/2020_07_31__10_53_04/planet.o5m --node_storage=map --user_resource_path=/mapsme/omim/data --preprocess=true 
[2020-07-31 10:56:28,130] INFO stages Stage Preprocess: finished in 0:00:03.943198
[2020-07-31 10:56:28,131] INFO stages Stage Features: start ...
[2020-07-31 10:56:28,133] INFO stages Test test_booking_data was skipped.
[2020-07-31 10:56:28,169] INFO gen_tool Run generator tool [generator_tool version 1596049554 c2d18fcf5f6962bbc232747afa940789355f5b64]: /mapsme/omim-build-release/generator_tool --threads_count=6 --data_path=/mapsme/generation/2020_07_31__10_53_04/intermediate_data --intermediate_data_path=/mapsme/generation/2020_07_31__10_53_04/intermediate_data --osm_file_type=o5m --osm_file_name=/mapsme/generation/2020_07_31__10_53_04/planet.o5m --node_storage=map --user_resource_path=/mapsme/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/mapsme/generation/2020_07_31__10_53_04/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true 
[2020-07-31 10:57:39,409] INFO env Create /mapsme/generation/2020_07_31__10_53_04/200731 ...
[2020-07-31 10:57:39,410] INFO stages Stage Features: finished in 0:01:11.278214
[2020-07-31 10:57:39,411] INFO stages Stage Mwm: start ...
[2020-07-31 12:02:28,045] INFO file Trying to download /mapsme/generation/2020_07_31__10_53_04/intermediate_data/mapsme_osm_subways.transit.json from http://osm-subway.maps.me/mapsme/latest.json.
[2020-07-31 12:09:23,046] INFO file File /mapsme/generation/2020_07_31__10_53_04/intermediate_data/mapsme_osm_subways.transit.json was downloaded from http://osm-subway.maps.me/mapsme/latest.json.
[2020-07-31 12:09:40,776] INFO env Create /mapsme/generation/2020_07_31__10_53_04/stats ...
[2020-07-31 12:09:40,806] INFO stages Stage Mwm: finished in 1:12:01.394547
[2020-07-31 12:09:40,806] ERROR env Uncaught exception: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 300, in <module>
    main()
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 296, in main
    generate_maps(env, from_stage)
  File "/mapsme/omim/tools/python/maps_generator/maps_generator.py", line 44, in generate_maps
    run_generation(env, stages, from_stage)
  File "/mapsme/omim/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/mapsme/omim/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/mapsme/omim/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages_declaration.py", line 174, in apply
    chunksize=1,
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mapsme/omim/tools/python/maps_generator/generator/stages_declaration.py", line 172, in <lambda>
    lambda c: StageMwm.make_mwm(c, env),
  File "/mapsme/omim/tools/python/maps_generator/generator/stages_declaration.py", line 194, in make_mwm
    StageMwmStatistics(country=country)(env)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 268, in apply
    method(obj, env, country, *args, logger=_logger, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 243, in apply
    method(obj, env, country, *args, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages_declaration.py", line 280, in apply
    steps.step_statistics(env, country, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/steps.py", line 342, in step_statistics
    os.path.join(env.paths.intermediate_data_path, f"{country}.stats"),
  File "/mapsme/omim/tools/python/maps_generator/generator/statistics.py", line 98, in make_stats
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by alexx7676** [comment]
[version.txt](https://github.com/mapsme/dockerfiles/files/5006998/version.txt)
[generation.log](https://github.com/mapsme/dockerfiles/files/5006991/generation.log)
[DownloadAndConvertPlanet.log](https://github.com/mapsme/dockerfiles/files/5006992/DownloadAndConvertPlanet.log)
[Features.log](https://github.com/mapsme/dockerfiles/files/5006993/Features.log)
[Mwm.log](https://github.com/mapsme/dockerfiles/files/5006995/Mwm.log)
[Preprocess.log](https://github.com/mapsme/dockerfiles/files/5006996/Preprocess.log)
[Uzbekistan.log](https://github.com/mapsme/dockerfiles/files/5006997/Uzbekistan.log)

**Comment by tatiana-yan** [comment]
Hello.
Add `STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt` to your config.

**Comment by alexx7676** [comment]
Doesn't work.
Here sould be other environment variable, not this one:
```${Developer:OMIM_PATH}```

**Comment by alexx7676** [comment]
I set ```/mapsme/omim``` instead of this variable. Now it runs. I'm waiting completion for now.

**Comment by alexx7676** [comment]
Now I've got another exception:
```[2020-07-31 14:27:46,551] ERROR env Uncaught exception: 'ascii' codec can't decode byte 0xe2 in position 475: ordinal not in range(128)```

[generation.log](https://github.com/mapsme/dockerfiles/files/5007701/generation.log)

**Comment by tatiana-yan** [comment]
Mwm generator was designed to work with utf-8 locale. So you can set locale (LC_ALL, LC_CTYPE) to "en_US.UTF-8"

or probably fix it with 

```diff
@@ -95,7 +95,7 @@ def format_res(res, t):
 
 
 def make_stats(config_path, stats_path):
-    with open(config_path) as f:
+    with open(config_path, 'r', encoding="utf-8") as f:
```

Another option -- you probably do not need result of statictics stage (we use it for our production map generation to compare new maps with previous generation, it does not affect mwm's). So as hot fix you can comment out make_statistics call.
It should be disableable with "--skip=Statistics" but I tried it and it looks like this option does not work. We'll fix it but it'll take some time so maybe hot fix will be better for you.

**Comment by tatiana-yan** [comment]
I checked, there is no bug, it's another option name. just run

```
$ docker run -v ~/projects/osm/generation:/mapsme/generation --rm -t maps_generator --config=/mapsme/generation/config.ini --countries="Uzbekistan" --skip="Coastline,MwmStatistics"
```

it should work with your original config too. We'll fix readme. Thank you for report.

**Comment by alexx7676** [comment]
There are two examples of usage in the file README.md. I think you should add parameter in both places.

**Comment by alexx7676** [comment]
Doesn't work again:
```$ docker run -v ~/projects/osm/generation:/mapsme/generation --rm -t maps_generator --config=/mapsme/generation/config.ini --countries="Uzbekistan" --skip="Coastline,MwmStatistics"```

```UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 414: ordinal not in range(128)```

[generation.log](https://github.com/mapsme/dockerfiles/files/5021486/generation.log)

My system is linux, docker also works in linux. Default locale is utf-8.

**Comment by maksimandrianov** [comment]
We fixed it in https://github.com/mapsme/dockerfiles/pull/5.
Please try to rebuild the docker container and run it again:
```
$ docker build --build-arg TAG=release-101 -t maps_generator .
$ docker run -v ~/projects/osm/generation:/mapsme/generation --rm -t maps_generator --config=/mapsme/generation/config.ini --countries="Uzbekistan" --skip="Coastline,MwmStatistics"
```

**Comment by alexx7676** [comment]
@maksimandrianov , дефект не решён. Я пересобрал контейнер, запустил, проблема осталась.

**Comment by alexx7676** [comment]
```
[2020-08-05 15:35:10,220] INFO env Start setup ...
[2020-08-05 15:35:10,221] INFO env Create /mapsme/tmp ...
[2020-08-05 15:35:10,221] INFO env Check osm tools ...
[2020-08-05 15:35:10,222] INFO env Create /mapsme/osmctools ...
[2020-08-05 15:35:10,223] INFO env Build osm tools ...
[2020-08-05 15:35:14,301] INFO env Check generator tool ...
[2020-08-05 15:35:14,302] INFO env Find generator tool in /mapsme/omim-build-release ...
[2020-08-05 15:35:14,302] INFO env Generator found - /mapsme/omim-build-release/generator_tool
[2020-08-05 15:35:14,302] INFO env Build name is 2020_08_05__15_35_14.
[2020-08-05 15:35:14,302] INFO env Build path is /mapsme/generation/2020_08_05__15_35_14.
[2020-08-05 15:35:14,303] INFO env Create /mapsme/generation/2020_08_05__15_35_14 ...
[2020-08-05 15:35:14,303] INFO env Create /mapsme/generation/2020_08_05__15_35_14/intermediate_data ...
[2020-08-05 15:35:14,303] INFO env Create /mapsme/generation/2020_08_05__15_35_14/intermediate_data/borders ...
[2020-08-05 15:35:14,303] INFO env Create /mapsme/generation/2020_08_05__15_35_14/draft ...
[2020-08-05 15:35:14,304] INFO env Create /mapsme/generation/2020_08_05__15_35_14/osm2ft ...
[2020-08-05 15:35:14,304] INFO env The following 1 maps will build: Uzbekistan.
[2020-08-05 15:35:14,304] INFO env Finish setup
[2020-08-05 15:35:14,305] INFO env Create /mapsme/generation/2020_08_05__15_35_14/logs ...
[2020-08-05 15:35:14,305] INFO stages Stage DownloadAndConvertPlanet: start ...
[2020-08-05 15:35:14,305] INFO env Create /mapsme/generation/2020_08_05__15_35_14/status ...
[2020-08-05 15:35:14,312] INFO file Trying to download /mapsme/generation/2020_08_05__15_35_14/planet.osm.pbf from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.
[2020-08-05 15:35:14,312] INFO file Trying to download /mapsme/generation/2020_08_05__15_35_14/planet.osm.pbf.md5 from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5.
[2020-08-05 15:35:14,661] INFO file File /mapsme/generation/2020_08_05__15_35_14/planet.osm.pbf.md5 was downloaded from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5.
[2020-08-05 15:36:12,369] INFO file File /mapsme/generation/2020_08_05__15_35_14/planet.osm.pbf was downloaded from http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.
[2020-08-05 15:36:14,573] INFO stages Stage DownloadAndConvertPlanet: finished in 0:01:00.267811
[2020-08-05 15:36:14,574] INFO stages Stage Preprocess: start ...
[2020-08-05 15:36:14,604] INFO gen_tool Run generator tool [generator_tool version 1596545786 992dec8e31a381a838392bb11d47f7d175f10a76]: /mapsme/omim-build-release/generator_tool --threads_count=1 --intermediate_data_path=/mapsme/generation/2020_08_05__15_35_14/intermediate_data --osm_file_type=o5m --osm_file_name=/mapsme/generation/2020_08_05__15_35_14/planet.o5m --node_storage=map --user_resource_path=/mapsme/omim/data --preprocess=true 
[2020-08-05 15:36:18,594] INFO stages Stage Preprocess: finished in 0:00:04.019951
[2020-08-05 15:36:18,595] INFO stages Stage Features: start ...
[2020-08-05 15:36:18,595] INFO stages Test test_booking_data was skipped.
[2020-08-05 15:36:18,624] INFO gen_tool Run generator tool [generator_tool version 1596545786 992dec8e31a381a838392bb11d47f7d175f10a76]: /mapsme/omim-build-release/generator_tool --threads_count=6 --data_path=/mapsme/generation/2020_08_05__15_35_14/intermediate_data --intermediate_data_path=/mapsme/generation/2020_08_05__15_35_14/intermediate_data --osm_file_type=o5m --osm_file_name=/mapsme/generation/2020_08_05__15_35_14/planet.o5m --node_storage=map --user_resource_path=/mapsme/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/mapsme/generation/2020_08_05__15_35_14/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true 
[2020-08-05 15:37:32,058] INFO env Create /mapsme/generation/2020_08_05__15_35_14/200805 ...
[2020-08-05 15:37:32,059] INFO stages Stage Features: finished in 0:01:13.463757
[2020-08-05 15:37:32,060] INFO stages Stage Mwm: start ...
[2020-08-05 16:39:36,966] INFO file Trying to download /mapsme/generation/2020_08_05__15_35_14/intermediate_data/mapsme_osm_subways.transit.json from http://osm-subway.maps.me/mapsme/latest.json.
[2020-08-05 16:47:10,706] INFO file File /mapsme/generation/2020_08_05__15_35_14/intermediate_data/mapsme_osm_subways.transit.json was downloaded from http://osm-subway.maps.me/mapsme/latest.json.
[2020-08-05 16:47:24,479] INFO stages Stage Mwm: finished in 1:09:52.418279
[2020-08-05 16:47:24,480] INFO stages Stage CountriesTxt: start ...
[2020-08-05 16:47:24,490] INFO stages Stage CountriesTxt: finished in 0:00:00.009156
[2020-08-05 16:47:24,490] ERROR env Uncaught exception: 'ascii' codec can't decode byte 0xd8 in position 414: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 300, in <module>
    main()
  File "/mapsme/omim/tools/python/maps_generator/__main__.py", line 296, in main
    generate_maps(env, from_stage)
  File "/mapsme/omim/tools/python/maps_generator/maps_generator.py", line 44, in generate_maps
    run_generation(env, stages, from_stage)
  File "/mapsme/omim/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/mapsme/omim/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/mapsme/omim/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages.py", line 371, in apply
    method(obj, env, *args, **kwargs)
  File "/mapsme/omim/tools/python/maps_generator/generator/stages_declaration.py", line 299, in apply
    env.paths.mwm_version,
  File "/mapsme/omim/tools/python/post_generation/hierarchy_to_countries.py", line 141, in hierarchy_to_countries
    vsosm = parse_borders_vs_osm(borders_vs_osm_csv_path)
  File "/mapsme/omim/tools/python/post_generation/hierarchy_to_countries.py", line 103, in parse_borders_vs_osm
    for line in f:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 414: ordinal not in range(128)
```

**Comment by maksimandrianov** [comment]
Можете показать лог сборки контейнера, т.е. результат:
```
docker build --build-arg TAG=release-101 -t maps_generator .
```

**Comment by alexx7676** [comment]
Лог шёл в консоль, результата нет.
Вызывал командой:
```docker build --no-cache --build-arg TAG=release-101 -t maps_generator .```
В логе ошибок не видел.
Если точно нужен лог, тогда выполню сборку повторно.

**Comment by alexx7676** [comment]
UPD: Нашёл причину. Сейчас ещё раз проверю.

**Comment by alexx7676** [comment]
Всё работает.
Извините за беспокойство.

**Comment by alexx7676** [comment]
Карта метрополитена Ташкента не доступна при сборке из докера.

**Comment by tatiana-yan** [comment]
чтобы было метро нужно указать в конфиге SUBWAY_URL, например

```
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
```

тот конфиг который приведён тут в readme минимальный и использует только осм (planet.osm). В наших production картах кроме данных которые мы берём из planet есть ещё много дополнительных источников, при этом у разных источников разные лицензии. Чтобы посмотреть какие вообще есть опции, посмотрите конфиг в документации к генератору: https://github.com/mapsme/omim/tree/master/tools/python/maps_generator .

Например, у вас также не будет изолиний и профиля высот в пеших маршрутах. Чтобы появились профили высот нужно выкачать данные SRTM/ASTER, убедившись что их лицензия вам подходит, и указать параметр SRTM_PATH.
Чтобы появились изолинии нужно выкачать те же SRTM/ASTER, потом обработать их нашей opensource тулзой https://github.com/mapsme/omim/tree/master/topography_generator и результат передать через параметр ISOLINES_PATH.

Также есть опциональные параметры, которые влияют на количество данных на выходе:
UGC_URL -- ссылка на sqlite с отзывами и рейтингами
HOTELS_URL -- ссылка на отели букинга
POPULARITY_URL -- ссылка на список популярных достопримечательностей
FOOD_URL -- ссылка для объединения кафе/ресторанов в сети
FOOD_TRANSLATIONS_URL -- ссылка на переводы названий сетей кафе/ресторанов на разные языки
UK_POSTCODES_URL -- ссылка на датасет с английскими индексами
US_POSTCODES_URL -- ссылка на датасет с американскими почтовыми индексами

Большая часть этих данных проприетарная, датасеты с индексами предоставляются под OGL и Creative Commons Attribution Share-Alike соответственно.

Данные метро, ссылку на которые я привела выше, получены из osm, их можно использовать на тех же правах что и osm. Также если вы хотите добавить какое-то метро которого нет в osm, либо добавить дополнительно железные дороги можно кастомизировать json.

Ещё у нас есть opensource тулзы которые конвертируют gtfx в такой json и надеюсь что мы скоро сможем поддержать также автобусы и другие типы транспорта (но там с лицензиями на данные тоже скорее всего всё будет туго, поэтому по умолчанию в конфигах для opensource сборок они не смогут появиться, но можно будет решить лицензионные вопросы с конкретными фидами и указать вручную).

**Comment by alexx7676** [comment]
@tatiana-yan , SYBWAY_URL указан. Вот мой конфиг:
```
[Main]
DEBUG: 0

[External]
PLANET_URL: http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf
PLANET_MD5_URL: http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf.md5
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
```
При сборке из исходников, не докер, карта метро есть.

**Comment by alexx7676** [comment]
Логи сборки в докере:
[generation.log](https://github.com/mapsme/dockerfiles/files/5046990/generation.log)
[Cleanup.log](https://github.com/mapsme/dockerfiles/files/5046991/Cleanup.log)
[ExternalResources.log](https://github.com/mapsme/dockerfiles/files/5046992/ExternalResources.log)
[CountriesTxt.log](https://github.com/mapsme/dockerfiles/files/5046993/CountriesTxt.log)
[Uzbekistan.log](https://github.com/mapsme/dockerfiles/files/5046994/Uzbekistan.log)
[Mwm.log](https://github.com/mapsme/dockerfiles/files/5046995/Mwm.log)
[Features.log](https://github.com/mapsme/dockerfiles/files/5046996/Features.log)
[Preprocess.log](https://github.com/mapsme/dockerfiles/files/5046997/Preprocess.log)
[DownloadAndConvertPlanet.log](https://github.com/mapsme/dockerfiles/files/5046998/DownloadAndConvertPlanet.log)

**Comment by tatiana-yan** [comment]
Вижу что попытка собрать transit была (в логе Uzbekistan.log). Можно посмотреть на итоговый файл mwm который получился?

**Comment by alexx7676** [comment]
https://yadi.sk/d/OOcslCQ9UHz1QQ

**Comment by tatiana-yan** [comment]
по логам выглядит так будто файл с json был неполный, такое редко но бывает (если например в osm сломали какую-то сеть, мы пытаемся всё чинить в osm чтобы метро не пропадало, но не всегда успеваем).

у меня сейчас собирается Ташкент с метро, в Uzbekistan.log

```
LOG TID(1) INFO   5.6915e-05 generator/transit_generator.cpp:205 BuildTransit() Building transit section for Uzbekistan mwmDir: /Users/t.yan/ma    ps_build/2020_08_10__15_54_35/draft/
LOG TID(1) INFO        7.282 routing/index_graph_loader.cpp:218 CreateIndexGraph() routing section for Uzbekistan loaded in 0.174153 seconds
LOG TID(1) INFO       9.9451 transit/transit_graph_data.cpp:263 Serialize() transit section is ready. Header: TransitHeader [version: 0, reserv    e: 0, stops: 36, gatesOffset: 999, edgesOffset: 5660, transfersOffset: 6644, linesOffset: 6729, shapesOffset: 7550, networksOffset: 16145, endOffset: 16157]
```

а у вас после BuildTransit пусто, как будто сети не было.
У вас сохранился latest.json с данными метро? можете сказать размер/хеш сумму?

```
$ md5sum /Users/t.yan/maps_build/2020_08_10__15_54_35/intermediate_data//mapsme_osm_subways.transit.json
4990a002a018491b749e669fa59afbbe  /Users/t.yan/maps_build/2020_08_10__15_54_35/intermediate_data//mapsme_osm_subways.transit.json
$ ls -lah /Users/t.yan/maps_build/2020_08_10__15_54_35/intermediate_data//mapsme_osm_subways.transit.json
-rw-r--r--  1 t.yan  staff   249M 10 авг 16:39 /Users/t.yan/maps_build/2020_08_10__15_54_35/intermediate_data//mapsme_osm_subways.transit.json
```

**Comment by alexx7676** [comment]
```
2020_08_08__09_07_30/intermediate_data$ md5sum mapsme_osm_subways.transit.json 
2b7eee344b7ca23418a6cf2b34b9101c  mapsme_osm_subways.transit.json

2020_08_08__09_07_30/intermediate_data$ ll mapsme_osm_subways.transit.json 
-rw-r--r-- 1 alex alex 129 авг  8 15:13 mapsme_osm_subways.transit.json
```

**Comment by alexx7676** [comment]
да, что-то он маленький
```
{
    "edges": [],
    "gates": [],
    "lines": [],
    "networks": [],
    "shapes": [],
    "stops": [],
    "transfers": []
}
```

**Comment by alexx7676** [comment]
Всё, собралась карта нормально. Файл метро скачался и схема отображается.
Спасибо.
